# Generated by Django 5.2.3 on 2025-06-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonneeBrute',
            new_name='Donnee',
        ),
    ]
